src/rich-text/markdown-serializer.ts
test/rich-text/markdown-serializer.test.ts

Our `markdown-serializer` uses custom escape logic when serializing text nodes entered in rich-text mode. This custom escaping is a little too eager and causes problems with URLs that contain underscores.
Take an URL like this entered in rich-text mode:
```
https://example.com/some_path_here
```
When switching over to markdown mode (or saving the document as markdown), this would get converted to:
```
https://example.com/some\_path\_here
```
which is problematic for URLs (and the autolinking we do) since it messes with the original URL.
This PR makes our custom escape logic more strict. I'm not sure if this is causing any regressions I didn't check yet, but our test suite is only raising shruggie as the single problem that might arise. With this tweak, you can still enter a shruggie in …

Fix overly eager underscore escaping

---

src/rich-text/plugins/link-tooltip.ts

When editing a link in rich-text mode, the input field gets extra bottom margin. That's due to a rather generous CSS rule in our `custom-components.less` that's got a lot of potential to mess with _any_ of our custom node views that use a `div` element:
```less
&.s-prose div {
margin-bottom: var(--s-prose-spacing);
```
Here's what it currently looks like:
In this PR I'm adding an explicit `mb0` to solve the immediate issue. We should think about making that custom CSS rule a little more specific.
Here's what it looks like with the fix in place:

Link popover: Fix messed up margin when editing

---

src/rich-text/inputrules.ts
test/e2e/editor.e2e.test.ts

[Feedback on meta](https://meta.stackexchange.com/a/360067/507720) shows that automatically converting quotes to smart quotes in rich-text mode doesn't spark joy.
The reasoning is sound. On a programming website quotes often occur in code samples. Converting them to smart quotes will break code samples and we all know how much people love copy/pasting code samples.
This PR removes the usage of a bunch of Prosemirror's input rules that could make developers' lives harder:
* converting quotes to smart quotes (both, single and double quotes)
* converting `...` to &hellip;
* converting `--` to —
All of the above are used in code in some form: `--` is a decrement operator, `...` is used as the spread operator in JS and quotes are... quotes.
We should not try to be smart about these things. If …

Remove smart quotes, ellipsis, emdash input rules

---

package-lock.json
site/index.html
site/index.ts
site/variants/dualeditor.html
src/shared/prosemirror-plugins/image-upload.ts

This pull request fixes issues #65 and #66.
#65 is solved by clearing the `uploadField.value `when switching between visible <--> invisible 
#66 is solved by making the `uploadField.id `unique per editor
For #66, I've added a second editor to the test page.

Fixed issue for two editors and cancelling an image upload

---

package-lock.json
src/external-plugins/stack-snippets.ts
src/shared/menu.ts
src/stacks-editor/editor.ts

`fl1` is getting replaced by the more explicit `fl-grow1` :v:

Switch away from deprecated grid classes

---

src/styles/custom-components.less

This fixes an error that occurs when attempting to run `npm run build` or similarly `npm run build:stackoverflow`. I tracked it down to the `chore: update Stacks dependencies` [commit](https://github.com/StackExchange/Stacks-Editor/commit/451051046fab4127d73eea38955de0d6fd49d4da) where it first started occurring.
1. Clone repository and pull down latest `main` branch.
2. Run `npm install`.
3. Run `npm run build:dev` OR `npm run start`. Both are successful.
4. Run `npm run build`. An error described below occurs.
```
> @stackoverflow/stacks-editor@0.4.1 build
> webpack --config config/webpack.prod.js
assets by status 459 KiB [cached] 45 assets
orphan modules 391 KiB [orphan] 50 modules
runtime modules 1.13 KiB 5 modules
modules by path ./node_modules/ 699 KiB
modules by path …
```

fix: add missing import reference for _stacks-mixins

---

src/shared/markdown-parser.ts
test/shared/markdown-parser.test.ts

See: [Emails are autolinked in the new Stacks editor](https://meta.stackexchange.com/q/370235) on MSE.

Do not autolink emails without the "mailto:" prefix

---

src/shared/menu.ts

Our icon-only toolbar needs some extra help for accessibility. This PR provides an `aria-label` for each item in the toolbar.

fix: add aria-labels to icon-only buttons

---

src/shared/prosemirror-plugins/image-upload.ts
test/shared/plugins/imageUploadPlugin.test.ts

This PR fixes two accessibility issues on the image uploader:
1. It adds an `alt` text to the preview image after you've selected an image to upload
2. It makes the "browse" button accessible via keyboard (tab navigation), allows triggering the file chooser via keyboard (Enter press on the "browse" button) and automatically focuses the "browse" button once the uploader opens
I'm still unhappy about the outline style used for the browse button. We're using `s-link` under the hood and this is the default style but to me it looks a little out of place. Any ideas?

Accessibility improvements for the image uploader

---

src/rich-text/node-views/image.ts

Fixes #53 very simply by rendering images in a `span` instead of a `div`.
I'm fully ready to learn that this is an overly-simple solution but it works fine* AFAICT 🤷‍♂️
---
*It works fine as-in there are no notable regressions. UX is a little lacking in being able move your cursor around freely, but that's a bigger issue and one that I consider out of scope for this  PR.

fix: treat images as inline

---

src/styles/custom-components.less

Fixes #86 and adds a few other high contrast enhancements to editor buttons.
Mentioning @allejo for visibility 👋
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

fix: increase button contrast in high contrast mode

---

src/rich-text/commands/index.ts
test/rich-text/commands/index.test.ts

Fixes #105
Another simple fix that hopefully is not too naïve. Also added a few tests that hopefully give us good heading-related coverage. Once this PR merges, I'd like to add the remaining tests outlined as `it.todo`s.

fix: toggle heading only when same level

---

src/commonmark/commands.ts
src/rich-text/commands/index.ts
src/shared/utils.ts
test/shared/utils.test.ts

resolves #46
---
After _far_ too much time trying to figure out how to get keyboard shortcuts from [src/rich-text/key-bindings.ts](https://github.com/StackExchange/Stacks-Editor/blob/main/src/rich-text/key-bindings.ts) to correspond to [src/rich-text/commands/index.ts](https://github.com/StackExchange/Stacks-Editor/blob/main/src/rich-text/commands/index.ts), I realized it would probably be fragile at best and impossible at worst.
I think the best way to add these shortcut labels is to just include them on the labels without pulling from anywhere.
This PR unifies tooltip text mostly by removing prefixed `Insert` (as in `Insert Code Block`).

feat: add shortcut labels to tooltips

---

src/styles/custom-components.less

fixes #143 
This is a simple one. Requesting a review just to see if there's any opinions about approach to overflow here (like, we could use `inherit` or `unset` if we wanted to be a little less prescriptive).
Examples with very long placeholder text (`This is placeholder text, so start typing…` repeated like 43 times)

fix(commonmark-editor): prevent placeholder clipping

---

src/commonmark/commands.ts
src/rich-text/commands/index.ts
src/shared/utils.ts

Closes #166
Change the shortcut keys to display with capital letters. No change to actual functionality.
Windows 10 Chrome 103

enhancement(editor) All shortcuts are shown in popovers with capital letters

---

CODE_OF_CONDUCT.md
site/layout.html

Having a distinct Code of Conduct file is a qualifier for Netlify's [open source plan](https://www.netlify.com/legal/open-source-policy/). We already lay out our code of conduct in the [CONTRIBUTING](https://github.com/StackExchange/Stacks-Editor/blob/main/CONTRIBUTING.md) file, but it doesn't hurt to have it split out as well.
Looking for a quick double check on this - does the content make sense the way I worded it? Once we're happy with the text, I'll copy this file to the other Stacks repos as well.

Add distinct Code of Conduct file

---

package-lock.json
package.json
src/shared/localization.ts
src/shared/menu/entries.ts
src/shared/menu/helpers.ts
test/shared/menu/helpers.test.ts

This is an attempt to solve the usability issue identified in this meta post: https://meta.stackoverflow.com/questions/422686/code-blocks-surrounded-by-triple-backtick-then-single-backtick
- Replace old `Codeblock` (filled) icon with the new `CodeblockAlt` (outlined) icon
- Create a separate area in the editor menu for code formatting (see mockup)
- Add additional help text in the Code block tooltip (see mockup)
Mockup:

fix(code-block): keep code-block and inline-code menu buttons side by side

---

src/commonmark/key-bindings.ts

Closes #240
Adds a keybinding for `Shift-Enter` and reuses the existing command bound to `Enter`
^ Could use some help with the above.  Not sure we need to super robustly test since we're just exporting an existing command as a new key binding
- Device: Desktop
- OS: Windows
- Browser: Chrome
- Version: 110
The default functionality comes from [`prosemirror-commands/src/commands.ts`](https://github.com/ProseMirror/prosemirror-commands/blob/7d895cae5224ad6d5bd6e705878811673b0314f7/src/commands.ts#L691-L692)
```ts
export const pcBaseKeymap: {[key: string]: Command} = {
"Enter": chainCommands(newlineInCode, createParagraphNear, liftEmptyBlock, splitBlock),
```
Which we import directly into our common mark key-bindings, along with any customizations we might like.  We could probably import …

fix(commonmark): allow shift-enter command

---

site/sample-plugins/code-detection.ts
site/sample-plugins/index.ts
site/views/plugins.html
src/shared/prosemirror-plugins/image-upload.ts
test/shared/prosemirror-plugins/image-upload.test.ts

Dispatch a custom event on image upload to allow plugin authors to pause the upload flow and decide to either abort or resume it based on async operations. 
- Visit `http://localhost:8080/plugins.html` or the [PR deploy preview](https://deploy-preview-249--stacks-editor.netlify.app/plugins.html)
- Upload an image in rich-text or commonmark mode
- A confirmation dialog should appear saying that code was detected in the image
- Click ok and observe a codeblock being inserted in the editor as opposed to the image being uploaded

feat(image-upload): dispatch event for intercepting image upload flow

---

src/shared/menu/plugin.ts

Closes [STACKS-382](https://stackoverflow.atlassian.net/browse/STACKS-382)
This PR adds `role="menuitem"` to buttons within a toolbar menu. It also adds `aria-hidden="true"` to the popover arrow since it's purely decorative.

fix(a11y): add menuitem role to menu buttons

---

src/shared/menu/plugin.ts

This is a minor accessibility tweak to improve the menu/menuitem relationship for controls

fix(a11y): make dropdown menuitems children of menu

---

src/shared/menu/helpers.ts
src/shared/menu/plugin.ts
test/commonmark/editor.e2e.test.ts

Closes [STACKS-383](https://stackoverflow.atlassian.net/browse/STACKS-383)
This PR ensures that the focused editor menu element retains focus when navigating via keyboard.
Previously, tabbing to a menu element then invoking it with <kbd>enter</kbd> would send focus to the "view" (aka the textarea). This would require those navigating with the keyboard to have to tab back to where they were to continue where they left off. This PR addresses this issue with the following changes:
1. Focus is no longer moved to the view unless editor menu item was clicked
2. The popover is only hidden if the popover menu item was clicked

fix(a11y): prevent refocus of textarea on keyboard navigation

---

src/shared/highlighting/hljs-instance.ts

[STACKS-346](https://stackoverflow.atlassian.net/browse/STACKS-346)
@stackoverflow/stacks-editor has a [reference](https://github.com/StackExchange/Stacks-Editor/blob/main/src/shared/highlighting/hljs-instance.ts#L17) to `require` for local developement environments which should be swapped with something ESM friendly like dynamic imports. This will allow ESM first tools such as vitest (and vite-node) to run smoothly when they are importing the editor.
Since webpack will exclude `highlightjs` at build time for production bundle there is no need of using dynamic import (which would have required to make the function async). Instead we can simply import `highlightjs` with a regular ESM import.
**How to test**
- Run `npm i`
- Run `npm run build` and check on webpack …

refactor(hljs): make hljs import for development environments ESM friendly

---

src/shared/menu/plugin.ts
src/styles/custom-components.css
test/shared/menu/plugin.test.ts

This change came from some issues I noticed while reviewing https://github.com/StackExchange/Stacks-Editor/pull/259. I took this opportunity to replace uses of `.is-disabled` with the `disabled` attribute which is ensures that disabled editor buttons act in accordance with our expectation of disabled UI. It has the added benefit of allowing us to some custom CSS, since Stacks buttons apply the expected styling on disabled buttons by targeting the `disabled` attribute.
@giamir I've opened this PR because I think it is fine to be reviewed, but no rush on this. It's just some work I performed in the process of reviewing https://github.com/StackExchange/Stacks-Editor/pull/259 and I felt was worth capturing.

fix(a11y): use disabled attribute instead of .is-disabled

---

src/rich-text/inputrules.ts
test/rich-text/inputrules.test.ts

[STACKS-520](https://stackoverflow.atlassian.net/browse/STACKS-520)
This PR is fixing an issue where Underscore Emphasis Autoformatting was triggered incorrectly. 
See the how to test section for more context.
The solution is leveraging a negative lookahead operator to make sure the first underscore is NOT preceded by a non-whitespace character.
- Open the editor instance in rich text mode
- Type manually (not copy pasting) `text_text_` (or `text__text__`)
- Observe auto formatting NOT kicking in and rewriting the above to text<em>text</em> (or text<strong>text</strong>)

fix(autoformatting): prevent autoformatting when the first underscore is preceded by a non-whitespace character

---

package-lock.json
package.json
src/shared/menu/helpers.ts
src/stacks-editor/editor.ts
src/styles/custom-components.css

Closes [STACKS-542](https://stackoverflow.atlassian.net/browse/STACKS-542)
This PR updates focus styles for buttons that are editor controls.
> **Note**
> This PR removes styling for `.s-btn-group__radio`. This element no longer exists (it's now `.s-btn-group--radio`).
> ~**Note**~
> ~This output of this PR may look incorrect until the @StackExchange/stacks dependency is updated beyond `2.0.9`.~

fix(controls): improve focus style to meet WCAG 2.2 AA

---

package-lock.json
package.json
src/stacks-editor/editor.ts
src/styles/custom-components.css

This PR updates Stacks Classic from 2.2.0 to 2.3.0 and makes updates to the markdown toggle to support the new button group styling.
@CGuindon when you have a sec, check out [the deploy preview](https://deploy-preview-293--stacks-editor.netlify.app/) and let me know if it looks ok to you. The button padding needed to be tweaked, so if you'd like the button padding tweaked further let me know.
Once this is approved, I'll cut a new stacks-editor release with this change and update our [Core PR for updating Stacks](https://github.com/StackEng/StackOverflow/pull/18992) with it, which will resolve the [button group issue mentioned there](https://github.com/StackEng/StackOverflow/pull/18992#pullrequestreview-1949611902).

build(deps-dev): bump @stackexchange/stacks from 2.2.0 to 2.3.0

---

src/rich-text/plugins/link-preview.ts
test/rich-text/plugins/link-preview.test.ts

Jira: [TEAMS-12649](https://stackoverflow.atlassian.net/browse/TEAMS-12649)
Related Core PR: https://github.com/StackEng/StackOverflow/pull/19095
Release Candidate: https://www.npmjs.com/package/@stackoverflow/stacks-editor/v/0.10.4-rc.0

fix(link-preview): ensure spinner is not shown indefinetely when no preview results are available

---

config/jest-unit.config.js
package-lock.json
package.json
src/rich-text/commands/index.ts
src/rich-text/commands/list.ts
src/rich-text/key-bindings.ts
src/shared/menu/entries.ts
test/rich-text/commands/list.test.ts
test/rich-text/list.e2e.test.ts
test/setup.ts

This PR enhance the editor rich text experience when editing lists. 
For more context about the issue see also [this document](https://docs.google.com/document/d/1rO6uRFIfELovhD5AAZRN-DuqV0JAUNhYhA7o1vjTLNc/edit?usp=sharing).
- Go to the [empty editor page](https://deploy-preview-298--stacks-editor.netlify.app/empty) and switch to rich text mode
Part 1:
- Write at least 3 items in 3 different rows (e.g. `Item 1` then `Enter`, `Item 2` then `Enter` and so on)
- Select all the 3 items 
- Click on the bullet list menu button (or shortcut `Meta+u`)
- Observe the items becoming a bulleted list of 3
- Click on the bullet list menu button again  (or shortcut `Meta+u`)
- Observe the items being removed from the list
- Repeat the above steps with the ordered list button (shortcut `Meta+o`)
Part 2: …

feat(list): enhance rich text list editing experience

---

config/webpack.common.js

Updates the `css-loader` settings in Webpack to fix build errors on my machine. I'm not entirely sure why the existing fix isn't enough, but I've added a more concise fix with a comment that also describes what's happening. I also updated `importLoaders` to the correct value while I was in there.
Side note: I'm not entirely sure why the `filter` rule is even necessary, since one would _think_ that the `/\.svg$/i` rule above would kick in correctly and the pipeline would continue on without doing anything else, but it doesn't. 🤷
<details><summary>Partial error message</summary>
```plaintext
... (12 similar errors preceding)
ERROR in data:image/svg+xml;,%3csvg width=%27100%25%27 height=%27100%25%27 xmlns=%27http://www.w3.org/2000/svg%27%3e%3crect width=%27100%25%27 …
```

Tweak webpack css-loader config to fix build errors

---

package-lock.json
src/styles/custom-components.css

Closes internal ticket \[STACKS-555\]. 
Currently the [button groups](https://stackoverflow.design/product/components/button-groups) in Stacks make the text bold on selected state. However the editor uses icons in place of text, which we obiously can't easily 'bolden'.
This PR adds some override CSS to button groups for the editor to invert the icon against a darker background, making it much more accessible.

feat: Invert button group icons for better contrast

---

src/rich-text/commands/index.ts
src/rich-text/key-bindings.ts
test/rich-text/commands/index.test.ts

Closes #191
This PR removes the custom logic that was attached to "arrow right" and "arrow down" keypresses.
These were added in #64 in an attempt to add some behaviour where people could exit code blocks by pressing arrow keys. Unfortunately that introduces bugs like this one, where you can't use the arrow keys to navigate _inside_ a code block any more - instead you get teleported out of it. Annoying!
After removing this code, things seem to work as I would expect them to anyway.
https://github.com/user-attachments/assets/a3186241-4d82-4353-8a30-cd4439462207
Tested on Chrome and Safari.
n/a

fix(code-blocks): remove buggy "exit code block" functionality

---

src/rich-text/commands/index.ts
src/rich-text/key-bindings.ts
test/rich-text/commands/index.test.ts

Closes #197
This PR make it so that if a code block is the first thing in a document, then when you press Enter at the start of that code block, a paragraph is created above.
This _only_ applies if you're at the start of the code block, _and_ only if that code block is the first thing in the doc.
https://github.com/user-attachments/assets/5116c278-ce1f-41e4-816b-7002198c1745
Chrome, Safari

fix(code-blocks): press Enter at start of first code block to create paragraph

---

site/index.ts
src/commonmark/editor.ts
src/commonmark/plugins/preview.ts

Fixes the issue described in [this meta post](https://meta.stackoverflow.com/questions/431137/stacks-editor-is-doing-rapid-layout-shift-as-i-edit-the-body-input). As the user types, preview container content is removed before the promise is resolved, causing the page layout to shift during the time it takes for the promise to resolve. The fix is to not clear the preview, rather wait for the content to be replaced when the promise is resolved. 
**Before**
[screen-capture (1).webm](https://github.com/user-attachments/assets/de33cf85-6be9-4d0b-a58a-3d389dfef417)
**After**
[screen-capture.webm](https://github.com/user-attachments/assets/74cc0864-59f8-4dfe-8a92-935b14587d78)
- Device: [e.g. desktop, iPhone6, etc.]
- OS: [e.g. …

fix(preview): Fix constant layout shift as preview rerenders

---

src/commonmark/commands.ts
test/commonmark/commands.test.ts

Fixes the issue described in [this meta post](https://meta.stackoverflow.com/questions/431670/creating-a-code-block-in-staging-ground-includes-one-additional-character-after). In markdown mode, the code block button surrounds one character extra than the user's selection. This PR corrects that, cleans up the code, and adds comments to make it more understandable. 
- Browser [e.g. chrome, safari]

fix(markdown): Fix code block selection off by one error

---

src/rich-text/commands/code-block.ts
src/shared/menu/entries.ts
test/rich-text/commands/code-block.test.ts
test/rich-text/test-helpers.ts

This PR addresses an issue raised on Meta here: https://meta.stackoverflow.com/questions/430988/what-causes-single-backticks-on-every-line-of-code
To address this, we disable the "inline code" button when the text selection includes linebreaks. Users should use code blocks instead of inline code when there are multiple lines.
The fix applies whether there are "real" linebreaks in the selection, or if there are "soft breaks" - these are what you get when you paste code into the Markdown view, then switch back to the rich text mode.
To test this, paste in the example code block from the Meta post:
```
from modules.prompt import create_conversation_prompt
from langchain.chains import ConversationChain
from langchain_core.output_parsers import StrOutputParser
from …
```

fix(inline-code): disallow "inline code" when selection has linebreaks

---

src/shared/menu/helpers.ts

This PR is a fix for the issue described here: https://meta.stackexchange.com/questions/407427/stacks-editor-toolbar-popup-not-visible-when-expending-upwards
Previously, the default for tooltips was set as `top`, but in practice they usually didn't do that, because there's not actually enough space _above_ the toolbar to display the tooltip. They normally display below the toolbar. The exception was when the window was short (or scrolled to the bottom). Without enough space below the toolbar either, the tooltips _did_ display above the toolbar, but then they hit an issue because the `overflow` CSS means that they weren't actually visible.
So, the fix here is simply to make them _always_ display below the toolbar. If that's below the line of the screen, that's at least better than …

fix(tooltips): tooltips always go below buttons

---

src/rich-text/inputrules.ts
test/rich-text/inputrules.test.ts

When using the rich text editor, we expect typed commonmark standards to be replaced with their visual equivalents.  This PR implements that for the commonmark standard of 4 spaces = code block. 
- Browser: Chrome
Reported on [meta](https://meta.stackexchange.com/questions/407251/when-typing-code-backslashes-are-automatically-inserted)

fix(rich-text-editor) interpret 4 spaces as a code block

---

src/rich-text/plugins/link-editor.ts
src/styles/custom-components.css
test/rich-text/plugins/link-editor.test.ts

This PR addresses various glitches with the link editor, as reported [on Meta](https://meta.stackexchange.com/questions/407489/hypertext-link-url-editing-seems-broken-or-at-least-difficult-to-use-in-rich-tex) and also in #170 and #200.
Here's an example showing the glitches when editing the post that is referred to in the Meta post above. The specific Markdown can be [found here](https://stackoverflow.com/revisions/7d43428c-6a5e-40ca-87b9-5b6473c2a313/view-source).
https://github.com/user-attachments/assets/f5263342-e4b7-4906-89a2-ea26f6d18522
Changes:
- **Link selection**. Previously, the link editor popup would display if any of the selected text contained a link. The popup would display details of only the first link in the selection. If you selected a huge block of text that happened …

fix(link-editor): link editor glitchiness tweaks

---

src/shared/localization.ts
src/shared/prosemirror-plugins/image-upload.ts
test/shared/prosemirror-plugins/image-upload.test.ts

[Jira](https://stackoverflow.atlassian.net/browse/DISCOCD-54)
[Meta](https://meta.stackexchange.com/questions/402075/the-stacks-editor-still-enforces-a-2-mib-image-size-limit-and-doesnt-support-t)
Allow passing through a param to control the file size limit of the image uploader. Default will remain 2 MiB. 
- Browser: chrome
Add any other context about the PR here.

feat: add passthrough max file size param to image uploader 

---

src/rich-text/editor.ts
src/rich-text/node-views/code-block.ts
src/rich-text/schema.ts
src/shared/highlighting/highlight-plugin.ts

This is another PR that is a precursor to adding a language picker dropdown to codeblocks, In the interests of keeping things small and reviewable.
There are no functional changes in this PR, but I've rearranged various things to make the current behaviour a little more explicit.
Code changes:
- removed `codeblockOverrideLanguage` from the options, as this is not used. The intention of this setting was to provide a default fallback language, presumably from a question's tags on Stack Overflow. But we're not using it (and a question can have multiple tags, so arguably this is not a useful design)
- there is logic for caching the auto-detected language from HighlightJS. This was stored in a node's `language` attribute, but since it's _only_ for the auto-detected language (and not for when a …

refactor(code-blocks): make code block language code clearer

---

.changeset/config.json
.github/workflows/release.yml
README.md
package-lock.json
package.json

Migrates change tracking to [changesets](https://github.com/changesets/changesets) (as per [this ADR](https://github.com/StackExchange/Stacks/pull/1576/files)).
This uses the standard implementation for changesets, and the same readme copy as in other examples.

Move to changesets for releases and publishing

---

.changeset/four-carrots-remain.md

This is a seperate changeset release to track changes up from 0.10.11 -> (hopefully) 0.11.1.
Typically these files would be produced alongside changes, but we have only recently moved to changeset, and wanted a means of tracking this intialization seperate from the GH action workflow changes.

Changeset catchup to latest release (should be 0.11.1)

---

.changeset/hip-forks-kiss.md
plugins/official/stack-snippets/src/commands.ts
plugins/official/stack-snippets/src/common.ts
plugins/official/stack-snippets/test/commands.test.ts
site/index.ts
src/commonmark/editor.ts
src/rich-text/editor.ts
src/shared/prosemirror-plugins/base-view-state.ts

In the Stacks Snippets plugin, we were relying on callers to append their changes to the document. This PR creates a callback parameter on the `openSnippetModal` function definition such that a function that will update the document can be called instead.
This allows us to amend existing snippets by their ID (which is available on the `snippetMetadata` passed to `openSnippetsModal`) by replacing thier contents. If it is not present, we append to the document.
- OS: Windows
- Browser: Chrome
- Version: 135.0.7049.114
I ran into an issue here where the plugin is trying to interact with the markdown-it parser while during a Prosemirror flow. We bundle these together at a top level …

Amend an existing snippet.

---

.changeset/fifty-tips-listen.md
plugins/official/stack-snippets/src/schema.ts
plugins/official/stack-snippets/src/snippet-view.ts
plugins/official/stack-snippets/test/snippet-view.test.ts
src/styles/icons.css

[Jira issue](https://stackoverflow.atlassian.net/browse/DISCOCD-81)
Adds a "Show/Hide" link to toggle the visibility of code snippets (not the results pane) in the StackSnippetView. This corresponds to how snippets preview worked in the old editor. The link is only rendered when the hide attribute is "true". 
- OS: [e.g. iOS]
- Browser: chrome
- Version [e.g. 22]
TODO: Need to add the same functionality to the preview pane in the MD+P mode.

feat(snippets): show/hide link functionality

---

.changeset/little-ears-rescue.md
plugins/official/stack-snippets/src/commands.ts
plugins/official/stack-snippets/src/stackSnippetPlugin.ts
plugins/official/stack-snippets/test/commands.test.ts
src/rich-text/commands/index.ts
src/rich-text/editor.ts
src/rich-text/key-bindings.ts
test/rich-text/commands/index.test.ts

- Fix unescapableCommand triggering on every arrow down press within the Snippet (e.g. in the a central language block, pressing down would cause a blank space despite not being at the end of the Snippet)
- Run unescapableCommand checks on up arrows too (e.g. you should be able to move above a snippet with the cursors)
- Allow External Plugins commands to override pre-definied editor commands
- Use the ability to override editor commands to swallow commands that are nonsensical for Snippets, and cause breaking changes to happen (e.g. inserting a line-rule in the middle of the Snippet)

fix(snippets): Fix unescapableCommand handling, swallow commands for snippets

---

.changeset/olive-snakes-wink.md
plugins/official/stack-snippets/src/commands.ts
plugins/official/stack-snippets/src/stackSnippetPlugin.ts
plugins/official/stack-snippets/test/commands.test.ts

Actually register the Snippet shortcut (rather than just displaying the hint in the button menu).
- OS: windows
- Browser: chrome
- Version: 135.0.7049.115
This has the potential to run differently on Macs and Windows. Needs pulled locally and tests run just to be sure.

Snippets: Actually register the snippet shortcut

---

.changeset/stale-jars-punch.md
plugins/official/stack-snippets/src/common.ts
plugins/official/stack-snippets/src/snippet-view.ts
plugins/official/stack-snippets/test/snippet-view.test.ts

Add a callback hook for snippet fullscreen/return, allowing calling code to handle any styling marshalling.

Add callback hooks for fullscreen/return

---

.changeset/lemon-glasses-cheat.md
plugins/official/index.ts

A couple of options interfaces passed to the StacksEditor are not exported. Therefore, I had to recreate these interfaces when I wanted to use them. See: 
https://github.com/StackEng/StackOverflow/blob/571e63834ee5920c9f5db16b97b84f94c85a872d/StackOverflow/_Scripts/islands/ask-question/src/shared/stackSnippets.ts#L18

fix(stack-snippet): expose stack-snippet options and metadata types

---

.changeset/mean-tools-hammer.md
README.md

Closes \[ISSUE_NUMBER\]. 
A clear and concise description of the changes included in this PR.
- Device: [e.g. desktop, iPhone6, etc.]
- OS: [e.g. iOS]
- Browser [e.g. chrome, safari]
- Version [e.g. 22]
Add any other context about the PR here.

chore(readme): add beta publishing section
